# Generated by Django 3.2 on 2021-09-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('school_level', models.CharField(choices=[('pri', 'Primaria'), ('sec', 'Secundaria'), ('pre', 'Pre-universitario'), ('uni', 'Universitario')], max_length=3, verbose_name='Nivel Escolar')),
                ('occupation', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ocupación')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('phone_or_place', models.CharField(blank=True, max_length=220, null=True, verbose_name='Teléfono o lugar')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'verbose_name': 'Promovente',
                'verbose_name_plural': 'Promoventes',
            },
        ),
    ]
