# Generated by Django 3.2 on 2022-02-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_last_name'),
        ('promoters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.person', verbose_name='Persona'),
        ),
    ]
