# Generated by Django 3.2 on 2022-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='Apellidos', max_length=250, null=True, verbose_name='Apellidos'),
        ),
    ]
