# Generated by Django 3.2 on 2022-02-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisms', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisms.organism', verbose_name='Organismo'),
        ),
    ]
