# Generated by Django 3.2 on 2021-09-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promoters', '0001_initial'),
        ('entities', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_date', models.DateField(verbose_name='Fecha de recepción')),
                ('management_level', models.CharField(max_length=220, verbose_name='Nivel de dirección que involucra')),
                ('problem', models.TextField(verbose_name='Planteamiento')),
                ('belonging_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belonging_entity', to='entities.entity')),
                ('demmanded_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demmanded_entity', to='entities.entity')),
                ('demmanded_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promoters.promoter')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
                'ordering': ['-reception_date'],
            },
        ),
    ]
